export interface CoinMeta {
  id: string;          // CoinGecko ID
  symbol: string;      // e.g. BTC
  name: string;        // e.g. Bitcoin
  color: string;       // brand hex
}

export const COINS: CoinMeta[] = [
  { id: 'bitcoin',           symbol: 'BTC',   name: 'Bitcoin',            color: '#F7931A' },
  { id: 'ethereum',          symbol: 'ETH',   name: 'Ethereum',           color: '#627EEA' },
  { id: 'tether',            symbol: 'USDT',  name: 'Tether',             color: '#26A17B' },
  { id: 'binancecoin',       symbol: 'BNB',   name: 'BNB',                color: '#F3BA2F' },
  { id: 'solana',            symbol: 'SOL',   name: 'Solana',             color: '#9945FF' },
  { id: 'ripple',            symbol: 'XRP',   name: 'XRP',                color: '#346AA9' },
  { id: 'usd-coin',          symbol: 'USDC',  name: 'USD Coin',           color: '#2775CA' },
  { id: 'staked-ether',      symbol: 'STETH', name: 'Lido Staked ETH',    color: '#00A3FF' },
  { id: 'dogecoin',          symbol: 'DOGE',  name: 'Dogecoin',           color: '#C2A633' },
  { id: 'cardano',           symbol: 'ADA',   name: 'Cardano',            color: '#0D1E2D' },
  { id: 'tron',              symbol: 'TRX',   name: 'TRON',               color: '#FF0013' },
  { id: 'avalanche-2',       symbol: 'AVAX',  name: 'Avalanche',          color: '#E84142' },
  { id: 'shiba-inu',         symbol: 'SHIB',  name: 'Shiba Inu',          color: '#FFA409' },
  { id: 'wrapped-bitcoin',   symbol: 'WBTC',  name: 'Wrapped Bitcoin',    color: '#F7931A' },
  { id: 'polkadot',          symbol: 'DOT',   name: 'Polkadot',           color: '#E6007A' },
  { id: 'chainlink',         symbol: 'LINK',  name: 'Chainlink',          color: '#2A5ADA' },
  { id: 'bitcoin-cash',      symbol: 'BCH',   name: 'Bitcoin Cash',       color: '#8DC351' },
  { id: 'near',              symbol: 'NEAR',  name: 'NEAR Protocol',      color: '#000000' },
  { id: 'matic-network',     symbol: 'MATIC', name: 'Polygon',            color: '#8247E5' },
  { id: 'uniswap',           symbol: 'UNI',   name: 'Uniswap',            color: '#FF007A' },
  { id: 'litecoin',          symbol: 'LTC',   name: 'Litecoin',           color: '#BFBBBB' },
  { id: 'leo-token',         symbol: 'LEO',   name: 'UNUS SED LEO',       color: '#F4900C' },
  { id: 'dai',               symbol: 'DAI',   name: 'Dai',                color: '#F5AC37' },
  { id: 'internet-computer', symbol: 'ICP',   name: 'Internet Computer',  color: '#29ABE2' },
  { id: 'ethereum-classic',  symbol: 'ETC',   name: 'Ethereum Classic',   color: '#328432' },
  { id: 'cosmos',            symbol: 'ATOM',  name: 'Cosmos Hub',         color: '#6F7390' },
  { id: 'filecoin',          symbol: 'FIL',   name: 'Filecoin',           color: '#0090FF' },
  { id: 'stellar',           symbol: 'XLM',   name: 'Stellar',            color: '#090909' },
  { id: 'monero',            symbol: 'XMR',   name: 'Monero',             color: '#FF6600' },
  { id: 'okb',               symbol: 'OKB',   name: 'OKB',                color: '#2B6FE6' },
  { id: 'hedera-hashgraph',  symbol: 'HBAR',  name: 'Hedera',             color: '#222222' },
  { id: 'kaspa',             symbol: 'KAS',   name: 'Kaspa',              color: '#49EACB' },
  { id: 'injective-protocol',symbol: 'INJ',   name: 'Injective',          color: '#00BAFF' },
  { id: 'the-open-network',  symbol: 'TON',   name: 'Toncoin',            color: '#0088CC' },
  { id: 'aptos',             symbol: 'APT',   name: 'Aptos',              color: '#00D9FF' },
  { id: 'optimism',          symbol: 'OP',    name: 'Optimism',           color: '#FF0420' },
  { id: 'arbitrum',          symbol: 'ARB',   name: 'Arbitrum',           color: '#28A0F0' },
  { id: 'vechain',           symbol: 'VET',   name: 'VeChain',            color: '#15BDFF' },
  { id: 'maker',             symbol: 'MKR',   name: 'Maker',              color: '#1AAB9B' },
  { id: 'aave',              symbol: 'AAVE',  name: 'Aave',               color: '#B6509E' },
  { id: 'stacks',            symbol: 'STX',   name: 'Stacks',             color: '#5546FF' },
  { id: 'quant-network',     symbol: 'QNT',   name: 'Quant',              color: '#E8761B' },
  { id: 'thorchain',         symbol: 'RUNE',  name: 'THORChain',          color: '#33FF99' },
  { id: 'theta-token',       symbol: 'THETA', name: 'Theta Network',      color: '#2AB8E6' },
  { id: 'fantom',            symbol: 'FTM',   name: 'Fantom',             color: '#1969FF' },
  { id: 'the-graph',         symbol: 'GRT',   name: 'The Graph',          color: '#6747ED' },
  { id: 'elrond-erd-2',      symbol: 'EGLD',  name: 'MultiversX',         color: '#23F7DD' },
  { id: 'sandbox',           symbol: 'SAND',  name: 'The Sandbox',        color: '#00ADEF' },
  { id: 'decentraland',      symbol: 'MANA',  name: 'Decentraland',       color: '#FF2D55' },
  { id: 'axie-infinity',     symbol: 'AXS',   name: 'Axie Infinity',      color: '#0055D5' },
  { id: 'gala',              symbol: 'GALA',  name: 'Gala',               color: '#7FD8E8' },
  { id: 'enjincoin',         symbol: 'ENJ',   name: 'Enjin Coin',         color: '#7866D5' },
  { id: 'chiliz',            symbol: 'CHZ',   name: 'Chiliz',             color: '#CD0124' },
  { id: 'curve-dao-token',   symbol: 'CRV',   name: 'Curve DAO',          color: '#840000' },
  { id: 'compound-ether',    symbol: 'COMP',  name: 'Compound',           color: '#00D395' },
  { id: 'yearn-finance',     symbol: 'YFI',   name: 'yearn.finance',      color: '#0657F9' },
  { id: 'synthetix-network-token', symbol: 'SNX', name: 'Synthetix',      color: '#00D1FF' },
  { id: 'loopring',          symbol: 'LRC',   name: 'Loopring',           color: '#1C60FF' },
  { id: 'sushi',             symbol: 'SUSHI', name: 'SushiSwap',          color: '#FA52A0' },
  { id: 'pancakeswap-token', symbol: 'CAKE',  name: 'PancakeSwap',        color: '#1FC7D4' },
  { id: '1inch',             symbol: '1INCH', name: '1inch',              color: '#D82122' },
  { id: 'balancer',          symbol: 'BAL',   name: 'Balancer',           color: '#1E1E1E' },
  { id: 'terra-luna-2',      symbol: 'LUNA',  name: 'Terra',              color: '#FFD83D' },
  { id: 'flow',              symbol: 'FLOW',  name: 'Flow',               color: '#00EF8B' },
  { id: 'kava',              symbol: 'KAVA',  name: 'Kava',               color: '#FF433E' },
  { id: 'band-protocol',     symbol: 'BAND',  name: 'Band Protocol',      color: '#516AFF' },
  { id: 'ocean-protocol',    symbol: 'OCEAN', name: 'Ocean Protocol',     color: '#592D97' },
  { id: 'dydx',              symbol: 'DYDX',  name: 'dYdX',               color: '#6966FF' },
  { id: 'zcash',             symbol: 'ZEC',   name: 'Zcash',              color: '#ECB244' },
  { id: 'dash',              symbol: 'DASH',  name: 'Dash',               color: '#008CE7' },
  { id: 'neo',               symbol: 'NEO',   name: 'Neo',                color: '#58BF00' },
  { id: 'iota',              symbol: 'MIOTA', name: 'IOTA',               color: '#242424' },
  { id: 'ontology',          symbol: 'ONT',   name: 'Ontology',           color: '#32A4BE' },
  { id: 'basic-attention-token', symbol: 'BAT', name: 'Basic Attention', color: '#FF5000' },
  { id: 'ankr',              symbol: 'ANKR',  name: 'Ankr',               color: '#2E5EFF' },
  { id: 'celo',              symbol: 'CELO',  name: 'Celo',               color: '#35D07F' },
  { id: 'nervos-network',    symbol: 'CKB',   name: 'Nervos Network',     color: '#3CC68A' },
  { id: 'livepeer',          symbol: 'LPT',   name: 'Livepeer',           color: '#00EB88' },
  { id: 'lisk',              symbol: 'LSK',   name: 'Lisk',               color: '#0D4EA0' },
  { id: 'storj',             symbol: 'STORJ', name: 'Storj',              color: '#2683FF' },
  { id: 'golem',             symbol: 'GLM',   name: 'Golem',              color: '#181EA9' },
  { id: 'numeraire',         symbol: 'NMR',   name: 'Numeraire',          color: '#050005' },
  { id: 'audius',            symbol: 'AUDIO', name: 'Audius',             color: '#CC0FE0' },
  { id: 'woo-network',       symbol: 'WOO',   name: 'WOO Network',        color: '#1DA2B4' },
  { id: 'blur',              symbol: 'BLUR',  name: 'Blur',               color: '#FF8700' },
  { id: 'sui',               symbol: 'SUI',   name: 'Sui',                color: '#4CA3FF' },
  { id: 'pepe',              symbol: 'PEPE',  name: 'Pepe',               color: '#479F53' },
  { id: 'bonk',              symbol: 'BONK',  name: 'Bonk',               color: '#F6A51C' },
  { id: 'worldcoin-wld',     symbol: 'WLD',   name: 'Worldcoin',          color: '#000000' },
  { id: 'fetch-ai',          symbol: 'FET',   name: 'Fetch.ai',           color: '#1C2BBA' },
  { id: 'render-token',      symbol: 'RNDR',  name: 'Render',             color: '#E84142' },
  { id: 'aleph-zero',        symbol: 'AZERO', name: 'Aleph Zero',         color: '#00CCAB' },
  { id: 'celestia',          symbol: 'TIA',   name: 'Celestia',           color: '#7B2BF9' },
  { id: 'altlayer',          symbol: 'ALT',   name: 'AltLayer',           color: '#FF4500' },
  { id: 'jito-governance-token', symbol: 'JTO', name: 'Jito',            color: '#85C93E' },
  { id: 'pyth-network',      symbol: 'PYTH',  name: 'Pyth Network',       color: '#E6DAFE' },
  { id: 'jupiter-exchange-solana', symbol: 'JUP', name: 'Jupiter',        color: '#C7F284' },
  { id: 'dogwifcoin',        symbol: 'WIF',   name: 'dogwifhat',          color: '#9945FF' },
  { id: 'bittensor',         symbol: 'TAO',   name: 'Bittensor',          color: '#AAAAAA' },
];

export const TOP_COINS = COINS.slice(0, 100);
