/**
 * weeklySentimentEnhanced.ts — CryptoVerse HQ Enhanced Weekly Sentiment Report
 * Collects price data, news, sentiment, generates comprehensive HTML report.
 * All users (basic report free, detailed analysis for Pro+).
 */
import { deepSeekAsk } from '@/lib/deepSeekClient';
import { fetchSentimentSnapshot } from '@/features/socialSentimentEngine';

const REPORT_KEY = 'cv_weekly_report';
const PREF_KEY = 'cv_weekly_pref';

export interface WeeklyReport {
  id: string; week: string; generatedAt: string;
  summary: string; marketOutlook: string;
  topPerformer: string; worstPerformer: string;
  tips: string[]; sentimentScore: number;
}

export function getReportPreference(): { enabled: boolean } {
  try { return JSON.parse(localStorage.getItem(PREF_KEY)||'{"enabled":true}'); } catch { return { enabled:true }; }
}
export function setReportPreference(pref: {enabled:boolean}): void {
  try { localStorage.setItem(PREF_KEY,JSON.stringify(pref)); } catch {}
}

export async function generateWeeklyReport(userPlan: string): Promise<WeeklyReport> {
  const week = `${new Date().getFullYear()}-W${Math.ceil(new Date().getDate()/7)}`;
  const fallback: WeeklyReport = {
    id:`wr_${week}`, week, generatedAt:new Date().toISOString(),
    summary:'Weekly market report generated by CryptoVerse HQ.', marketOutlook:'Neutral',
    topPerformer:'BTC', worstPerformer:'Unknown', tips:['Diversify your portfolio','Set stop-losses','Stay informed'],
    sentimentScore:50,
  };

  try {
    const snap = await fetchSentimentSnapshot();
    const prompt = `Weekly crypto report. Market mood: ${snap.moodLabel} (${snap.marketMood}/100). Top coins: ${snap.coins.slice(0,5).map(c=>`${c.coin}:${c.score}`).join(',')}. Generate: 2-sentence summary, market outlook (Bullish/Bearish/Neutral), best/worst performer, 3 trading tips. JSON: {"summary":"...","marketOutlook":"...","topPerformer":"BTC","worstPerformer":"...","tips":["...","...","..."],"sentimentScore":N}. Only JSON.`;
    const r = await deepSeekAsk(prompt);
    const j = JSON.parse(r.replace(/```json\n?/g,'').replace(/\n?```/g,'').trim());
    const report = { ...fallback, ...j, id:`wr_${week}`, week, generatedAt:new Date().toISOString() };
    saveReport(report);
    return report;
  } catch { return fallback; }
}

export function saveReport(report: WeeklyReport): void {
  try {
    const h = JSON.parse(localStorage.getItem(REPORT_KEY)||'[]') as WeeklyReport[];
    const filtered = h.filter(r=>r.week!==report.week);
    filtered.push(report);
    localStorage.setItem(REPORT_KEY,JSON.stringify(filtered.slice(-12)));
  } catch {}
}

export function getReportHistory(): WeeklyReport[] {
  try { return JSON.parse(localStorage.getItem(REPORT_KEY)||'[]'); } catch { return []; }
}
